/* ============================================================
   data.js — All static data for Nigeria 2027 Platform
   Sources: NBS, INEC, BudgIT State of States 2025,
            CBN, DMO, SBM Intelligence, ACLED, RMAFC
   ============================================================ */

const NG2027 = {};

/* ── Election Dates ── */
NG2027.ELECTIONS = {
  presidential: new Date('2027-01-16T08:00:00'),
  governorship:  new Date('2027-02-06T08:00:00'),
};

/* ── Economic History (2015–2025) ── */
NG2027.ECONOMIC = {
  years: ['2015','2016','2017','2018','2019','2020','2021','2022','2023','2024','2025'],
  inflation:    [9.0, 15.7, 16.5, 12.1, 11.4, 13.2, 17.0, 21.3, 28.9, 32.7, 33.2],
  exchangeRate: [197, 315,  360,  362,  360,  380,  410,  435,  907,  1310, 1580],
  nationalDebt: [12.6,17.4, 21.7, 24.4, 27.4, 32.9, 38.0, 46.3, 87.4, 121.7,134.3],
  securityFatalities: [11500,9600,6800,7200,8100,9400,10200,9800,7600,6100,5700],
};

/* ── Accountability Slides ── */
NG2027.SLIDES = [
  {
    id: 'inflation',
    cat: 'Inflation Crisis',
    headline: 'Consumer prices rose 369% in a decade',
    body: "Nigeria's headline inflation climbed from a broadly manageable 9.0% in 2015 to 33.2% by early 2025. Food inflation hit 40.2% in early 2024, eroding household purchasing power at its fastest pace since the 1990s. The CBN's aggressive rate hikes to 26.25% in 2024 failed to stem the spiral, with energy subsidy removal compounding cost-of-living pressure.",
    metricLabel: 'Headline Inflation Rate (2025)',
    metricValue: '33.2%',
    metricDelta: '↑ from 9.0% in 2015 — a 369% increase',
    source: 'NBS CPI Reports · CBN MPC Communiqués',
    chartKey: 'inflation',
    chartLabel: 'CPI (%) — 2015 to 2025',
    chartFmt: v => v.toFixed(1) + '%',
  },
  {
    id: 'exchange',
    cat: 'Naira Collapse',
    headline: '₦197/$ to ₦1,580/$: A 702% devaluation',
    body: "The naira has lost over 87% of its value against the US dollar since 2015. Two critical inflection points: the 2023 Tinubu-era FX unification which triggered a near-instantaneous 60% devaluation, and 2024 CBN interventions that briefly stabilised markets before further depreciation. Remittance inflows and FX reserves remain under structural pressure.",
    metricLabel: 'USD/NGN Exchange Rate (2025)',
    metricValue: '₦1,580/$',
    metricDelta: '↑ from ₦197/$ in 2015 — a 702% depreciation',
    source: 'CBN FX Market Data · FMDQ OTC Exchange',
    chartKey: 'exchangeRate',
    chartLabel: '₦/$ Rate — 2015 to 2025',
    chartFmt: v => '₦' + v.toLocaleString() + '/$',
  },
  {
    id: 'debt',
    cat: 'Debt Explosion',
    headline: 'Public debt surged 966%: ₦12.6tn → ₦134.3tn',
    body: "Nigeria's total public debt grew nearly tenfold over the decade. The most dramatic acceleration occurred post-2022 as FX losses inflated external debt in naira terms and Ways & Means financing expanded. DMO data shows debt service consumed 97.6 kobo of every naira of federal revenue in 2023, leaving minimal fiscal space for capital expenditure and social services.",
    metricLabel: 'Total Public Debt (2025)',
    metricValue: '₦134.3tn',
    metricDelta: '966% increase from ₦12.6tn in 2015',
    source: 'DMO Quarterly Debt Reports · BudgIT FY2025',
    chartKey: 'nationalDebt',
    chartLabel: '₦ Trillion — 2015 to 2025',
    chartFmt: v => '₦' + v.toFixed(1) + 'tn',
  },
  {
    id: 'security',
    cat: 'Security Crisis',
    headline: '5,700+ killed in Q1 2025 alone',
    body: "SBM Intelligence and ACLED data shows Nigeria has recorded over 100,000 conflict-related fatalities between 2015 and 2025, driven by Boko Haram/ISWAP terrorism in the North East, farmer-herder conflicts across the Middle Belt, and surging banditry in the North West. Despite military offensives, no zone has achieved durable peace. Economic cost estimated at over $1bn annually in lost productivity.",
    metricLabel: 'Security Fatalities (Q1 2025)',
    metricValue: '~5,700',
    metricDelta: '10-year cumulative total: 100,000+',
    source: 'SBM Intelligence · ACLED Nigeria · NIS',
    chartKey: 'securityFatalities',
    chartLabel: 'Annual Fatalities — 2015 to 2025',
    chartFmt: v => v.toLocaleString(),
  },
];

/* ── State Data ── */
NG2027.STATES = [
  {
    name: 'Kano', code: 'KN', capital: 'Kano', zone: 'North West',
    governor: 'Abba Kabir Yusuf', party: 'NNPP',
    pop2026_m: 17.4, gdpPct: 3.1,
    igr2024_bn: 28.6, faac2024_bn: 187.3, faacGrowth: 112.4,
    debt: { total: 196.8, domestic: 121.4, external: 75.4, dtr: 89.7 },
    unemployment: 34.2, poverty: 68.4,
    security: 'High Risk',
    industries: ['Agriculture', 'Textiles', 'Trade', 'Leather'],
    notes: 'Kano IGR remains critically low relative to its population size. FAAC dependency ratio stands at ~86.7%, making the state highly vulnerable to federal revenue shocks. Security challenges in the metro area continue to suppress FDI and industrial activity.',
    source: 'NBS, BudgIT State of States 2025, RMAFC',
    verified: 'Q1 2025',
  },
  {
    name: 'Lagos', code: 'LA', capital: 'Ikeja', zone: 'South West',
    governor: 'Babajide Sanwo-Olu', party: 'APC',
    pop2026_m: 24.2, gdpPct: 29.0,
    igr2024_bn: 843.0, faac2024_bn: 213.5, faacGrowth: 104.1,
    debt: { total: 1241.6, domestic: 387.4, external: 854.2, dtr: 118.2 },
    unemployment: 14.3, poverty: 4.5,
    security: 'Moderate',
    industries: ['Finance', 'Tech', 'Ports/Logistics', 'Entertainment', 'Manufacturing'],
    notes: 'Lagos accounts for ~29% of national GDP and generates the highest IGR in Nigeria by a wide margin. Despite robust revenues, debt-to-revenue ratio exceeds 100% due to aggressive infrastructure financing. External debt component (World Bank, IFC, bilateral) is significant.',
    source: 'NBS, BudgIT State of States 2025, LASG Revenue Office',
    verified: 'Q1 2025',
  },
  {
    name: 'Rivers', code: 'RV', capital: 'Port Harcourt', zone: 'South South',
    governor: 'Siminalayi Fubara', party: 'PDP',
    pop2026_m: 8.3, gdpPct: 7.4,
    igr2024_bn: 181.2, faac2024_bn: 312.7, faacGrowth: 118.9,
    debt: { total: 364.1, domestic: 198.4, external: 165.7, dtr: 74.1 },
    unemployment: 22.1, poverty: 31.7,
    security: 'High Risk',
    industries: ['Oil & Gas', 'Ports', 'Petrochemicals', 'Fishing'],
    notes: 'Rivers receives among the highest FAAC allocations due to derivation revenue from oil. Political instability in 2024-25 has dampened investor confidence. Port Harcourt remains strategically critical to national oil infrastructure.',
    source: 'NBS, BudgIT State of States 2025, RMAFC',
    verified: 'Q1 2025',
  },
  {
    name: 'Kaduna', code: 'KD', capital: 'Kaduna', zone: 'North West',
    governor: 'Uba Sani', party: 'APC',
    pop2026_m: 9.4, gdpPct: 2.8,
    igr2024_bn: 42.1, faac2024_bn: 148.6, faacGrowth: 108.3,
    debt: { total: 183.4, domestic: 112.7, external: 70.7, dtr: 107.2 },
    unemployment: 29.4, poverty: 58.2,
    security: 'Critical',
    industries: ['Agriculture', 'Mining', 'Textiles', 'Cattle trade'],
    notes: 'Kaduna faces a protracted security crisis driven by ethnic conflict and banditry. Its debt-to-revenue ratio exceeds 100%, indicating fiscal distress.',
    source: 'NBS, BudgIT State of States 2025',
    verified: 'Q1 2025',
  },
  {
    name: 'Ogun', code: 'OG', capital: 'Abeokuta', zone: 'South West',
    governor: 'Dapo Abiodun', party: 'APC',
    pop2026_m: 6.1, gdpPct: 3.6,
    igr2024_bn: 94.8, faac2024_bn: 89.4, faacGrowth: 103.7,
    debt: { total: 143.2, domestic: 88.1, external: 55.1, dtr: 78.4 },
    unemployment: 18.2, poverty: 19.3,
    security: 'Moderate',
    industries: ['Manufacturing', 'Agriculture', 'Real Estate', 'Industrials'],
    notes: 'Ogun has the highest concentration of manufacturing industries in Nigeria due to proximity to Lagos. IGR continues to grow driven by industrial zones in Sagamu and Agbara.',
    source: 'NBS, BudgIT State of States 2025',
    verified: 'Q1 2025',
  },
  {
    name: 'Enugu', code: 'EN', capital: 'Enugu', zone: 'South East',
    governor: 'Peter Mbah', party: 'PDP',
    pop2026_m: 4.7, gdpPct: 1.8,
    igr2024_bn: 31.6, faac2024_bn: 74.8, faacGrowth: 106.1,
    debt: { total: 96.4, domestic: 61.2, external: 35.2, dtr: 89.9 },
    unemployment: 24.1, poverty: 42.6,
    security: 'Moderate',
    industries: ['Coal/Mining', 'Agriculture', 'Services', 'Trade'],
    notes: 'Enugu is the commercial capital of the South East. Security has improved relative to 2022-23 levels. IGR growth is modest but trending upward with new tax administration reforms.',
    source: 'NBS, BudgIT State of States 2025',
    verified: 'Q1 2025',
  },
];

/* ── Parties ── */
NG2027.PARTIES = [
  { abbr: 'APC',  full: "All Progressives Congress",           chair: 'Abdullahi Ganduje',  founded: 2013, zone: 'National', ideology: 'Progressive conservatism', color: '#166534' },
  { abbr: 'PDP',  full: "People's Democratic Party",           chair: 'Umar Damagum (Ag.)', founded: 1998, zone: 'National', ideology: 'Social democracy', color: '#1e40af' },
  { abbr: 'LP',   full: 'Labour Party',                        chair: 'Julius Abure',       founded: 2002, zone: 'National', ideology: 'Social liberalism', color: '#991b1b' },
  { abbr: 'NNPP', full: 'New Nigeria Peoples Party',           chair: 'Rufai Aliyu Hanga',  founded: 2001, zone: 'National', ideology: 'Populism / North-focus', color: '#6b21a8' },
  { abbr: 'SDP',  full: 'Social Democratic Party',             chair: 'Shehu Gabam',        founded: 1989, zone: 'National', ideology: 'Social democracy', color: '#0e7490' },
  { abbr: 'APGA', full: 'All Progressives Grand Alliance',     chair: 'Edozie Njoku',       founded: 2003, zone: 'South East', ideology: 'Igbo nationalism / progressivism', color: '#065f46' },
  { abbr: 'ADC',  full: 'African Democratic Congress',         chair: 'Ralph Okey Nwosu',   founded: 2005, zone: 'National', ideology: 'Liberal democracy', color: '#1e3a8a' },
  { abbr: 'YPP',  full: 'Young Progressives Party',            chair: 'Bishop Amakwe',      founded: 2017, zone: 'National', ideology: 'Youth-led progressivism', color: '#14532d' },
  { abbr: 'AAC',  full: 'African Action Congress',             chair: 'Omoyele Sowore',     founded: 2017, zone: 'National', ideology: 'Activism / anti-corruption', color: '#7c2d12' },
  { abbr: 'PRP',  full: "People's Redemption Party",           chair: 'Falalu Bello',       founded: 1978, zone: 'National', ideology: 'Leftist populism', color: '#1d4ed8' },
  { abbr: 'ADP',  full: 'Action Democratic Party',             chair: 'Sani Musa',          founded: 2017, zone: 'National', ideology: 'Liberal conservatism', color: '#374151' },
  { abbr: 'NRM',  full: 'National Rescue Movement',            chair: 'Alkali Buba',        founded: 2012, zone: 'National', ideology: 'Centrist nationalism', color: '#374151' },
  { abbr: 'APM',  full: 'Action Peoples Movement',             chair: 'Suleiman Adamu',     founded: 2018, zone: 'National', ideology: 'Centrist', color: '#374151' },
  { abbr: 'BP',   full: 'Boot Party',                          chair: 'N/A',                founded: 2021, zone: 'National', ideology: 'Activist / social justice', color: '#374151' },
  { abbr: 'DPP',  full: 'Democratic Peoples Party',            chair: 'Biodun Ogunsakin',   founded: 2003, zone: 'National', ideology: 'Conservative democracy', color: '#374151' },
  { abbr: 'ACPN', full: 'African Council of Patriotic Nationals',chair:'Gani Galadima',     founded: 1999, zone: 'National', ideology: 'Pan-African nationalism', color: '#374151' },
  { abbr: 'SPN',  full: "Socialist Party of Nigeria",          chair: 'Abiodun Bamigboye',  founded: 2017, zone: 'National', ideology: 'Democratic socialism', color: '#374151' },
  { abbr: 'ZLP',  full: 'Zenith Labour Party',                 chair: 'Dan Nwanyanwu',      founded: 1999, zone: 'National', ideology: 'Labour interests', color: '#374151' },
  { abbr: 'PPC',  full: "Peoples Positive Change",             chair: 'Chike Ukaegbu',      founded: 2015, zone: 'National', ideology: 'Centrist reform', color: '#374151' },
];

/* ── Zones ── */
NG2027.ZONES = [
  { name: 'North West',   states: ['Kano','Kaduna','Sokoto','Zamfara','Kebbi','Jigawa','Katsina'], pop_m: 49.8 },
  { name: 'North East',   states: ['Borno','Adamawa','Gombe','Bauchi','Yobe','Taraba'], pop_m: 26.3 },
  { name: 'North Central',states: ['Niger','Benue','Kogi','Kwara','Nasarawa','Plateau','FCT'], pop_m: 33.1 },
  { name: 'South West',   states: ['Lagos','Ogun','Oyo','Osun','Ondo','Ekiti'], pop_m: 47.6 },
  { name: 'South East',   states: ['Enugu','Anambra','Imo','Ebonyi','Abia'], pop_m: 23.2 },
  { name: 'South South',  states: ['Rivers','Delta','Edo','Cross River','Akwa Ibom','Bayelsa'], pop_m: 22.8 },
];

/* ── Hub Sample Posts ── */
NG2027.HUB_POSTS = [
  {
    id: 1,
    user: 'Aisha_DataNG',
    avatar: 'A',
    zone: 'Kano, North West',
    starLevel: 4,
    truthScore: 91,
    type: 'verified',
    time: '2 hours ago',
    title: 'Kano 2024 FAAC Allocation vs Actual Budget Release',
    body: 'Cross-referencing RMAFC disbursements with Kano State budget implementation report (Q3 2024): only 38.4% of allocated FAAC funds reached approved capital projects. Overhead and personnel consumed ₦112bn of the ₦187bn total. Source: Kano State Budget Office, Q3 2024 Report.',
    tags: ['#FAAC', '#Kano', '#BudgetTransparency'],
    upvotes: 247,
    citations: 3,
  },
  {
    id: 2,
    user: 'ChidiBudgIT',
    avatar: 'C',
    zone: 'Enugu, South East',
    starLevel: 5,
    truthScore: 97,
    type: 'verified',
    time: '5 hours ago',
    title: 'Debt Service vs Capital Expenditure: A 10-State Comparison',
    body: 'Analysis of 10 states from BudgIT State of States 2025 shows median debt service ratio is 41.3% of total expenditure, while median capital spend is 22.8%. In 4 states (Zamfara, Adamawa, Kebbi, Borno) debt service exceeds capital expenditure by over 200%. This pattern is structurally unsustainable.',
    tags: ['#DebtProfile', '#CapEx', '#BudgIT'],
    upvotes: 389,
    citations: 5,
  },
  {
    id: 3,
    user: 'FatimahNG2027',
    avatar: 'F',
    zone: 'Abuja, FCT',
    starLevel: 2,
    truthScore: 68,
    type: 'citizen',
    time: '1 day ago',
    title: 'Market prices in Karu: Ground-level inflation report',
    body: 'Bean flour up 340% since January 2023 in Karu market, Abuja. Garri (yellow) was ₦600/kg in early 2023, now ₦2,400/kg. This aligns with NBS food inflation data but the lived reality is even worse. Posting receipts as photo evidence.',
    tags: ['#FoodInflation', '#CitizenReport', '#Abuja'],
    upvotes: 142,
    citations: 1,
  },
  {
    id: 4,
    user: 'SecurityWatch_NG',
    avatar: 'S',
    zone: 'Kaduna, North West',
    starLevel: 3,
    truthScore: 84,
    type: 'verified',
    time: '2 days ago',
    title: 'Kaduna Security Incidents Q1 2025: ACLED vs Official Reports',
    body: 'ACLED logs 312 conflict events in Kaduna State for Q1 2025 (Jan–Mar). Official government figures acknowledged 187. The 67% discrepancy is consistent with underreporting patterns observed since 2019. Southern Kaduna LGAs account for 61% of incidents.',
    tags: ['#Security', '#Kaduna', '#ACLED'],
    upvotes: 213,
    citations: 2,
  },
];
